apiVersion: v1
kind: Pod
metadata:
  name: shell-demo-cm-volume
  labels:
    name: shell-demo-cm-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: car-volume
      mountPath: /etc/cars
  volumes:
    - name: car-volume
      configMap:
        name: carmap