apiVersion: v1
kind: Pod
metadata:
  name: nettool
  labels:
    name: nettool
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"