apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-one
spec:
  selector:
    matchLabels:
      app: secondary
  replicas: 2
  template:
    metadata:
      labels:
        app: secondary
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeSelector: 
        system: secondOne
