apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two-ingress
spec:
  selector:
    matchLabels:
      app: nginx-two-ingress
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-two-ingress
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
          protocol: TCP